version: '3.8'
name: rust-nexus
services:
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_DB: rust_nexus_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
